### ISSUE TITLE
Help with LDAP and ldap_search_pwd

### ISSUE THREAD

**Issue by slowpoke115** [walkamongus/puppet-harbor#7]
Firstly, you've done an excellent job here; I've managed to get a fairly fully configured harbor server with minimal manual intervention needed, I would like to implement LDAP though which leaves me with two queries:

Ldap_search_password looks to be a valid field on the harbor docs (here: https://github.com/goharbor/harbor/blob/master/docs/configure_user_settings.md), why does your code prevent this from being used by swagger? If need be I'll copy the curl examples, I think perhaps I've misunderstood the class though.

I'm also a little confused by the relationship of "manifests/config.pp" (which includes lots of ldap config) and the need for any configuration at all via "harbor_user_settings". When I set any values in the main harbor class, they seem to get ignored (e.g ldap_search_pwd).

**Comment by walkamongus** [comment]
@slowpoke115 currently, the API doesn't expose `ldap_search_pwd` so it can't be set via the type. As for the `config.pp` params you mentioned, they were left over from the big configuration change between 1.8.x and 1.9.x. I've merged in a PR that cleans up all the orphaned params (since the lates module version drops 1.8 support) and I'll get a release out to the Forge soon.
